CREATE TABLE USERS
(
	USERID BigINT IDENTITY NOT NULL,
	USERNAME NVARCHAR(MAX) NOT NULL,
	PASSWORD binary(32) NOT NULL,
	SALT binary(16) NOT NULL,
	ROLE INT NOT NULL DEFAULT 0,
	PRIMARY KEY (USERID)
);

CREATE TABLE MANGA
(
	MANGAID BigINT IDENTITY NOT NULL,
	NAME NVARCHAR(MAX) NOT NULL,
	AUTHOR NVARCHAR(MAX),
	ARTIST NVARCHAR(MAX),
	PUBLISHER NVARCHAR(MAX),
	STATUS NVARCHAR(MAX),
	VOLUMES INT,
	LANGUAGE NVARCHAR(MAX),
	GENRE NVARCHAR(MAX),
	IMAGE NVARCHAR(MAX),
	DESCRIPTION NVARCHAR(MAX),
	PRIMARY KEY (MANGAID)
);

CREATE TABLE USERMANGA
(
	USERID BigINT NOT NULL,
	MANGAID BigINT NOT NULL,
	OWNED INT,
	COMMENT NVARCHAR(MAX),
	SCORE INT,
	PRIMARY KEY (USERID, MANGAID)
);

ALTER TABLE USERMANGA
ADD CONSTRAINT FK_USERMANGA_USERS FOREIGN KEY (USERID)
REFERENCES USERS(USERID);
CREATE INDEX IX_FK_USERMANGA_USERS ON USERMANGA(USERID);

ALTER TABLE USERMANGA
ADD CONSTRAINT FK_USERMANGA_MANGA FOREIGN KEY (MANGAID)
REFERENCES MANGA(MANGAID);
CREATE INDEX IX_FK_USERMANGA_MANGA ON USERMANGA(MANGAID);

CREATE TABLE RELEASE
(
	RELEASEID BigINT IDENTITY NOT NULL,
	MANGAID BigINT NOT NULL,
	VOLUME INT,
	ACTIVE BIT,
	RELEASEDATE datetime,
	PRIMARY KEY (RELEASEID)
);

ALTER TABLE RELEASE
ADD CONSTRAINT FK_RELEASE_MANGA FOREIGN KEY (MANGAID)
REFERENCES MANGA(MANGAID);
CREATE INDEX IX_FK_RELEASE_MANGA ON RELEASE(MANGAID);